/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreNosRouteImport } from './routes/sobre-nos'
import { Route as ContactosRouteImport } from './routes/contactos'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as ServicosPeritagensTecnicasRouteImport } from './routes/servicos/peritagens-tecnicas'
import { Route as ServicosGestaoDeProjectosRouteImport } from './routes/servicos/gestao-de-projectos'
import { Route as ServicosAvaliacaoEConsultoriaRouteImport } from './routes/servicos/avaliacao-e-consultoria'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'

const SobreNosRoute = SobreNosRouteImport.update({
  id: '/sobre-nos',
  path: '/sobre-nos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactosRoute = ContactosRouteImport.update({
  id: '/contactos',
  path: '/contactos',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicosPeritagensTecnicasRoute =
  ServicosPeritagensTecnicasRouteImport.update({
    id: '/servicos/peritagens-tecnicas',
    path: '/servicos/peritagens-tecnicas',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicosGestaoDeProjectosRoute =
  ServicosGestaoDeProjectosRouteImport.update({
    id: '/servicos/gestao-de-projectos',
    path: '/servicos/gestao-de-projectos',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicosAvaliacaoEConsultoriaRoute =
  ServicosAvaliacaoEConsultoriaRouteImport.update({
    id: '/servicos/avaliacao-e-consultoria',
    path: '/servicos/avaliacao-e-consultoria',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contactos': typeof ContactosRoute
  '/sobre-nos': typeof SobreNosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/servicos/avaliacao-e-consultoria': typeof ServicosAvaliacaoEConsultoriaRoute
  '/servicos/gestao-de-projectos': typeof ServicosGestaoDeProjectosRoute
  '/servicos/peritagens-tecnicas': typeof ServicosPeritagensTecnicasRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contactos': typeof ContactosRoute
  '/sobre-nos': typeof SobreNosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/servicos/avaliacao-e-consultoria': typeof ServicosAvaliacaoEConsultoriaRoute
  '/servicos/gestao-de-projectos': typeof ServicosGestaoDeProjectosRoute
  '/servicos/peritagens-tecnicas': typeof ServicosPeritagensTecnicasRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contactos': typeof ContactosRoute
  '/sobre-nos': typeof SobreNosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/servicos/avaliacao-e-consultoria': typeof ServicosAvaliacaoEConsultoriaRoute
  '/servicos/gestao-de-projectos': typeof ServicosGestaoDeProjectosRoute
  '/servicos/peritagens-tecnicas': typeof ServicosPeritagensTecnicasRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contactos'
    | '/sobre-nos'
    | '/blog/$slug'
    | '/servicos/avaliacao-e-consultoria'
    | '/servicos/gestao-de-projectos'
    | '/servicos/peritagens-tecnicas'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contactos'
    | '/sobre-nos'
    | '/blog/$slug'
    | '/servicos/avaliacao-e-consultoria'
    | '/servicos/gestao-de-projectos'
    | '/servicos/peritagens-tecnicas'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contactos'
    | '/sobre-nos'
    | '/blog/$slug'
    | '/servicos/avaliacao-e-consultoria'
    | '/servicos/gestao-de-projectos'
    | '/servicos/peritagens-tecnicas'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactosRoute: typeof ContactosRoute
  SobreNosRoute: typeof SobreNosRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ServicosAvaliacaoEConsultoriaRoute: typeof ServicosAvaliacaoEConsultoriaRoute
  ServicosGestaoDeProjectosRoute: typeof ServicosGestaoDeProjectosRoute
  ServicosPeritagensTecnicasRoute: typeof ServicosPeritagensTecnicasRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre-nos': {
      id: '/sobre-nos'
      path: '/sobre-nos'
      fullPath: '/sobre-nos'
      preLoaderRoute: typeof SobreNosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactos': {
      id: '/contactos'
      path: '/contactos'
      fullPath: '/contactos'
      preLoaderRoute: typeof ContactosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/peritagens-tecnicas': {
      id: '/servicos/peritagens-tecnicas'
      path: '/servicos/peritagens-tecnicas'
      fullPath: '/servicos/peritagens-tecnicas'
      preLoaderRoute: typeof ServicosPeritagensTecnicasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/gestao-de-projectos': {
      id: '/servicos/gestao-de-projectos'
      path: '/servicos/gestao-de-projectos'
      fullPath: '/servicos/gestao-de-projectos'
      preLoaderRoute: typeof ServicosGestaoDeProjectosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicos/avaliacao-e-consultoria': {
      id: '/servicos/avaliacao-e-consultoria'
      path: '/servicos/avaliacao-e-consultoria'
      fullPath: '/servicos/avaliacao-e-consultoria'
      preLoaderRoute: typeof ServicosAvaliacaoEConsultoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactosRoute: ContactosRoute,
  SobreNosRoute: SobreNosRoute,
  BlogSlugRoute: BlogSlugRoute,
  ServicosAvaliacaoEConsultoriaRoute: ServicosAvaliacaoEConsultoriaRoute,
  ServicosGestaoDeProjectosRoute: ServicosGestaoDeProjectosRoute,
  ServicosPeritagensTecnicasRoute: ServicosPeritagensTecnicasRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
